[project]
name = "sitequery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langgraph>=0.2.45",
]

[dependency-groups]
dev = [
    "jupyterlab>=4.3.0",
]
